apiVersion: v1
kind: Service
metadata:
  name: react-demo-service
  labels:
    app: react-demo-app
spec:
  selector:
    app: react-demo-app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer