apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Demo Project

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      name: aks-demo-cluster

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
